/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	hardikdevv1alpha1 "github.com/hdkshingala/deploymentcreator/pkg/apis/hardik.dev/v1alpha1"
	versioned "github.com/hdkshingala/deploymentcreator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/hdkshingala/deploymentcreator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/hdkshingala/deploymentcreator/pkg/client/listers/hardik.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DeploymentCreatorInformer provides access to a shared informer and lister for
// DeploymentCreators.
type DeploymentCreatorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DeploymentCreatorLister
}

type deploymentCreatorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDeploymentCreatorInformer constructs a new informer for DeploymentCreator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeploymentCreatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeploymentCreatorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDeploymentCreatorInformer constructs a new informer for DeploymentCreator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeploymentCreatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HardikV1alpha1().DeploymentCreators(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HardikV1alpha1().DeploymentCreators(namespace).Watch(context.TODO(), options)
			},
		},
		&hardikdevv1alpha1.DeploymentCreator{},
		resyncPeriod,
		indexers,
	)
}

func (f *deploymentCreatorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeploymentCreatorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deploymentCreatorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&hardikdevv1alpha1.DeploymentCreator{}, f.defaultInformer)
}

func (f *deploymentCreatorInformer) Lister() v1alpha1.DeploymentCreatorLister {
	return v1alpha1.NewDeploymentCreatorLister(f.Informer().GetIndexer())
}
